DROP TABLE IF EXISTS INVOICEITEM;

DROP TABLE IF EXISTS INVOICE;

DROP TABLE IF EXISTS OFFICEADDON;

DROP TABLE IF EXISTS LEASE;

DROP TABLE IF EXISTS LEASETYPE;

DROP TABLE IF EXISTS DESKHOLDER;

DROP TABLE IF EXISTS OFFICE;

DROP TABLE IF EXISTS REFERRALSOURCE;

DROP TABLE IF EXISTS OFFICETYPE;

CREATE TABLE OFFICETYPE -- OT
(
	OFFICETYPECODE DECIMAL(2, 0) CONSTRAINT PK_OFFICE_OFFICETYPECODE PRIMARY KEY CONSTRAINT NN_OFFICE_OFFICETYPECODE NOT NULL,
	OFFICETYPEDESCRIPTION VARCHAR(35) CONSTRAINT NN_OFFICE_OFFICETYPEDESCRIPTION NOT NULL CONSTRAINT UQ_OFFICETYPE_OFFICETYPEDESCRIPTION UNIQUE -- UQ MEANS UNIQUE, VALUES IN THIS COLUMN CANNOT HAVE MATCHING VALUES
);

SELECT
	*
FROM
	OFFICETYPE;

CREATE TABLE REFERRALSOURCE -- RS
(
	REFERRALSOURCECODE DECIMAL(2, 0) CONSTRAINT PK_REFERRALSOURCE_REFERRALSOURCECODE PRIMARY KEY CONSTRAINT NN_REFERRALSOURCE_REFERRALSOURCECODE NOT NULL,
	REFERRALSOURCEDESCRIPTION VARCHAR(30) CONSTRAINT NN_REFERRALSOURCE_REFERRALSOURCEDESCRIPTION NOT NULL CONSTRAINT UK_REFERRALSOURCE_REFERRALSOURCEDESCRIPTION UNIQUE
);

SELECT
	*
FROM
	REFERRALSOURCE;

CREATE TABLE OFFICE (
	OFFICENUMBER DECIMAL(3, 0) CONSTRAINT PK_OFFICE_OFFICENUMBER PRIMARY KEY CONSTRAINT NN_OFFICE_OFFICENUMBER NOT NULL,
	MONTHLYRENT DECIMAL(6, 2) CONSTRAINT NN_OFFICE_MONTHLYRENT NOT NULL CONSTRAINT CK_OFFICE_MONTHLYRENT_GREQZERO CHECK (MONTHLYRENT >= 0) CONSTRAINT DF_OFFICE_MONTHLYRENT_ZERO DEFAULT 0,
	SQUAREFOOTAGE DECIMAL(6, 2) CONSTRAINT NN_OFFICE_SQUAREFOOTAGE NOT NULL,
	BOOKSHELFYN CHAR(1) CONSTRAINT NN_OFFICE_BOOKSHELFYN NOT NULL CONSTRAINT CK_OFFICE_BOOKSHELFYN_YN CHECK (BOOKSHELFYN IN ('Y', 'N')) CONSTRAINT DF_OFFICE_BOOKSHELFYN_N DEFAULT ('N'),
	EXTRAFILINGCABINETYN CHAR(1) CONSTRAINT NN_OFFICE_EXTRAFILINGCABINETYN NOT NULL,
	MEETINGTABLEYN CHAR(1) CONSTRAINT NN_OFFICE_MEETINGTABLEYN NOT NULL,
	WINDOWQUANTITY DECIMAL(2, 0) CONSTRAINT NN_OFFICE_WINDOWQUANTITY NOT NULL CONSTRAINT CK_OFFICE_WINDOWQUANTITY_GRZERO CHECK (WINDOWQUANTITY > 0) CONSTRAINT DF_OFFICE_WINDOWQUANTITY_ONE DEFAULT 1,
	WINDOWSTATUS CHAR(1) CONSTRAINT NN_OFFICE_WINDOWSTATUS NOT NULL CONSTRAINT CK_OFFICE_WINDOWSTATUS CHECK (WINDOWSTATUS IN ('O', 'F')),
	OFFICETYPECODE DECIMAL(2, 0) CONSTRAINT NN_OFFICE_OFFICETYPECODE NOT NULL CONSTRAINT FK_OFFICE_OFFICETYPECODE_OFFICETYPE_OFFICETYPECODE REFERENCES OFFICETYPE (OFFICETYPECODE)
);

SELECT
	*
FROM
	OFFICE;

CREATE TABLE DESKHOLDER -- DH
(
	DESKHOLDERID CHAR(6) CONSTRAINT PK_DESKHOLDER_DESKHOLDERID PRIMARY KEY CONSTRAINT NN_DESKHOLDER_DESKHOLDERID NOT NULL,
	FIRSTNAME VARCHAR(35) CONSTRAINT NN_DESKHOLDER_FIRSTNAME NOT NULL,
	LASTNAME VARCHAR(40) CONSTRAINT NN_DESKHOLDER_LASTNAME NOT NULL,
	COMPANYNAME VARCHAR(55) CONSTRAINT NN_DESKHOLDER_COMPANYNAME NULL,
	EMAILADDRESS VARCHAR(75) CONSTRAINT NN_DESKHOLDER_EMAILADDRESS NOT NULL,
	CELLPHONENUMBER CHAR(10) CONSTRAINT NN_DESKHOLDER_CELLPHONENUMBER NOT NULL CONSTRAINT CK_DESKHOLDER_CELLPHONENUMBER_10DIGITS CHECK (CELLPHONENUMBER ~ '^[1-9][0-9]{9}$'),
	CREDITCARDNUMBER VARCHAR(16) CONSTRAINT NL_DESKHOLDER_CREDITCARDNUMBER NULL,
	REFERRALSOURCECODE DECIMAL(2, 0) CONSTRAINT NN_DESKHOLDER_REFERRALSOURCECODE NOT NULL CONSTRAINT FK_DESKHOLDER_REFERRALSOURCECODE_RS_REFERRALSOURCECODE REFERENCES REFERRALSOURCE (REFERRALSOURCECODE)
);

SELECT
	*
FROM
	DESKHOLDER;

CREATE TABLE LEASETYPE -- LT
(
	LEASETYPENUMBER DECIMAL(2, 0) CONSTRAINT PK_LEASETYPE_LEASETYPENUMBER PRIMARY KEY CONSTRAINT NN_LEASETYPE_LEASETYPENUMBER NOT NULL,
	LEASETYPEDESCRIPTION VARCHAR(50) CONSTRAINT NN_LEASETYPE_LEASETYPEDESCRIPTION NOT NULL
);

SELECT
	*
FROM
	LEASETYPE;

CREATE TABLE LEASE -- LSE
(
	LEASENUMBER DECIMAL(6, 0) CONSTRAINT PK_LEASE_LEASENUMBER PRIMARY KEY CONSTRAINT NN_LEASE_LEASENUMBER NOT NULL,
	STARTDATE TIMESTAMP CONSTRAINT NN_LEASE_STARTDATE NOT NULL CONSTRAINT CK_LEASE_STARTDATE_GREQ01JAN2020 CHECK (
		STARTDATE >= TO_TIMESTAMP('01-JAN-2020', 'DD-MON-YYYY')
	) CONSTRAINT DF_LEASE_STARTDATE_CURRENTDATE DEFAULT CURRENT_DATE,
	ENDDATE TIMESTAMP CONSTRAINT NL_LEASE_ENDDATE NULL,
	TOTALLEASECOST DECIMAL(15, 2) CONSTRAINT NL_LEASE_TOTALLEASECOST NULL,
	TOTALLEASEPRICE DECIMAL(15, 2) CONSTRAINT NL_LEASE_TOTALLEASEPRICE NULL,
	OFFICENUMBER DECIMAL(3, 0) CONSTRAINT NN_LEASE_OFFICENUMBER NOT NULL CONSTRAINT FK_LEASE_OFFICENUMBER REFERENCES OFFICE (OFFICENUMBER),
	DESKHOLDERID CHAR(6) CONSTRAINT NN_LEASE_DESKHOLDERID NOT NULL CONSTRAINT FK_LEASE_DESKHOLDERID_DESKHOLDER_DESKHOLDERID REFERENCES DESKHOLDER (DESKHOLDERID),
	LEASETYPENUMBER DECIMAL(2, 0) CONSTRAINT NN_LEASE_LEASETYPENUMBER NOT NULL CONSTRAINT FK_LEASE_LEASETYPENUMBER_LEASETYPE_LEASETYPENUMBER REFERENCES LEASETYPE (LEASETYPENUMBER)
);

SELECT
	*
FROM
	LEASE;

CREATE TABLE OFFICEADDON -- OAO
(
	ADDONNUMBER DECIMAL(4, 0) CONSTRAINT PK_OFFICEADDON_AONUM PRIMARY KEY CONSTRAINT NN_OFFICEADDON_AONUM NOT NULL,
	ADDONDESCRIPTION VARCHAR(45) CONSTRAINT NN_OFFICEADDON_ADDONDESCRIPTION NOT NULL,
	CURRENTCOST DECIMAL(6, 2) CONSTRAINT NN_OFFICEADDON_CURRENTCOST NOT NULL,
	CURRENTPRICE DECIMAL(6, 2) CONSTRAINT NN_OFFICEADDON_CURRENTPRICE NOT NULL,
	DISCOUNT DECIMAL(3, 0) CONSTRAINT NN_OFFICEADDON_DISCOUNT NULL
);

SELECT
	*
FROM
	OFFICEADDON;

CREATE TABLE INVOICE -- Inv
(
	INVOICENUMBER DECIMAL(6, 0) CONSTRAINT PK_INVOICE_INVOICENUMBER PRIMARY KEY CONSTRAINT NN_INVOICE_INVOICENUMBER NOT NULL,
	INVOICEDATE TIMESTAMP CONSTRAINT NN_INVOICE_INVOICEDATE NOT NULL,
	PAIDYN CHAR(1) CONSTRAINT NL_INVOICE_PAIDYN NULL,
	INVOICEGST DECIMAL(9, 2) CONSTRAINT NN_INVOICE_INVOICEGST NOT NULL,
	INVOICETOTAL DECIMAL(11, 2) CONSTRAINT NN_INVOICE_INVOICETOTAL NOT NULL,
	LEASENUMBER DECIMAL(6, 0) CONSTRAINT NN_INVOICE_LEASENUMBER NOT NULL CONSTRAINT FK_INVOICE_LEASENUMBER_LEASE_LEASENUMBER REFERENCES LEASE (LEASENUMBER)
);

SELECT
	*
FROM
	INVOICE;

CREATE TABLE INVOICEITEM -- II
(
	INVOICENUMBER DECIMAL(6, 0) CONSTRAINT NN_INVOICEITEM_INVOICENUMBER NOT NULL CONSTRAINT FK_INVOICEITEM_INVOICENUMBER_INVOICE_INVOICENUMBER REFERENCES INVOICE (INVOICENUMBER),
	ADDONNUMBER DECIMAL(4, 0) CONSTRAINT NN_INVOICEITEM_ADDONNUMBER NOT NULL CONSTRAINT FK_INVOICEITEM_ADDONNUMBER_OFFICEADDON_ADDONNUMBER REFERENCES OFFICEADDON (ADDONNUMBER),
	QUANTITYSOLD DECIMAL(5, 0) CONSTRAINT NN_INVOICEITEM_QUANTITYSOLD NOT NULL,
	INVOICEADDONCOST DECIMAL(6, 2) CONSTRAINT NN_INVOICEITEM_INVOICEADDONCOST NOT NULL,
	INVOICEADDONPRICE DECIMAL(6, 2) CONSTRAINT NN_INVOICEITEM_INVOICEADDONPRICE NOT NULL,
	CONSTRAINT PK_INVOICEITEM_INVOICENUMBER_ADDONNUMBER PRIMARY KEY (INVOICENUMBER, ADDONNUMBER)
);

SELECT
	*
FROM
	INVOICEITEM;

-- PostgreSQL
-- Delete all old records
DELETE FROM INVOICEITEM;

DELETE FROM INVOICE;

DELETE FROM OFFICEADDON;

DELETE FROM LEASE;

DELETE FROM LEASETYPE;

DELETE FROM DESKHOLDER;

DELETE FROM OFFICE;

DELETE FROM REFERRALSOURCE;

DELETE FROM OFFICETYPE;

-- Insert Into OfficeType
INSERT INTO
	OFFICETYPE (OFFICETYPECODE, OFFICETYPEDESCRIPTION)
VALUES
	(6, 'Virtual Office (Full Service)');

INSERT INTO
	OFFICETYPE (OFFICETYPECODE, OFFICETYPEDESCRIPTION)
VALUES
	(4, 'Shared Office');

INSERT INTO
	OFFICETYPE (OFFICETYPECODE, OFFICETYPEDESCRIPTION)
VALUES
	(3, 'Office Suite');

INSERT INTO
	OFFICETYPE (OFFICETYPECODE, OFFICETYPEDESCRIPTION)
VALUES
	(5, 'Virtual Office (Address only)');

INSERT INTO
	OFFICETYPE (OFFICETYPECODE, OFFICETYPEDESCRIPTION)
VALUES
	(2, 'Double Office');

INSERT INTO
	OFFICETYPE (OFFICETYPECODE, OFFICETYPEDESCRIPTION)
VALUES
	(1, 'Single Office');

-- Insert Into ReferralSource
INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(7, 'Twitter post');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(12, 'Existing Desk Holder Referral');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(13, 'Newspaper');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(6, 'Facebook post/group');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(2, 'Google Ads');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(10, 'Email Campaign');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(8, 'Instagram post/story');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(4, 'YouTube Ads');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(16, 'Other');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(3, 'Facebook Ads');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(17, 'Previous Desk Holder');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(11, 'Radio');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(15, 'Walk-In');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(9, 'Other social media');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(18, 'Business Partner Referral');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(1, 'Search Engine');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(5, 'Other social media advertising');

INSERT INTO
	REFERRALSOURCE (REFERRALSOURCECODE, REFERRALSOURCEDESCRIPTION)
VALUES
	(14, 'Word of mouth');

-- Insert Into Office
INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(217, 1100, 400, 'Y', 'Y', 'N', 4, 'F', 3);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(234, 1400, 300, 'Y', 'Y', 'Y', 2, 'O', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(228, 1900, 250, 'Y', 'N', 'Y', 1, 'O', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(223, 1750, 250, 'N', 'Y', 'Y', 2, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(204, 650, 300, 'N', 'Y', 'N', 5, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(172, 1950, 250, 'Y', 'Y', 'Y', 5, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(156, 600, 450, 'N', 'Y', 'N', 4, 'F', 4);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(179, 1600, 250, 'N', 'Y', 'Y', 1, 'O', 3);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(221, 1150, 400, 'Y', 'N', 'N', 5, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(118, 850, 300, 'N', 'N', 'Y', 2, 'F', 2);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(174, 1250, 400, 'Y', 'Y', 'N', 2, 'F', 3);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(196, 750, 100, 'Y', 'Y', 'N', 1, 'O', 5);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(207, 950, 300, 'Y', 'N', 'Y', 5, 'O', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(122, 1300, 200, 'N', 'N', 'Y', 3, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(245, 1900, 450, 'N', 'N', 'N', 1, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(129, 1550, 300, 'Y', 'N', 'N', 3, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(166, 850, 400, 'Y', 'N', 'N', 3, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(233, 1550, 200, 'Y', 'Y', 'N', 1, 'F', 2);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(210, 1450, 300, 'N', 'Y', 'Y', 4, 'F', 4);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(109, 1250, 400, 'N', 'N', 'Y', 1, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(158, 1000, 200, 'N', 'N', 'N', 1, 'O', 2);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(148, 750, 200, 'N', 'Y', 'Y', 2, 'F', 1);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(145, 550, 300, 'Y', 'Y', 'Y', 1, 'O', 3);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(128, 1000, 450, 'N', 'N', 'N', 3, 'F', 3);

INSERT INTO
	OFFICE (
		OFFICENUMBER,
		MONTHLYRENT,
		SQUAREFOOTAGE,
		BOOKSHELFYN,
		EXTRAFILINGCABINETYN,
		MEETINGTABLEYN,
		WINDOWQUANTITY,
		WINDOWSTATUS,
		OFFICETYPECODE
	)
VALUES
	(248, 850, 300, 'N', 'Y', 'Y', 4, 'O', 3);

-- Insert Into DeskHolder
INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'SHA001',
		'Maria',
		'Shailer',
		NULL,
		'mshailer12@sohu.com',
		7043626443,
		NULL,
		15
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'GIA001',
		'Mead',
		'Gianasi',
		NULL,
		'mgianasi7@twitpic.com',
		9814097192,
		NULL,
		15
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'WIN001',
		'Zolly',
		'Wingatt',
		NULL,
		'zwingatt4@home.pl',
		3774357423,
		'372301310747573',
		1
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'BRE001',
		'Consuela',
		'Brear',
		'Zava',
		'cbreark@parallels.com',
		3195091759,
		NULL,
		6
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'OUL001',
		'Carson',
		'Oullette',
		'Skyvu',
		'coullette1@mtv.com',
		7165753443,
		'372301971559465',
		12
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'ING001',
		'Mack',
		'Inglesfield',
		NULL,
		'minglesfieldv@soup.io',
		8928403652,
		'5007666130770787',
		10
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'EIL001',
		'Brandon',
		'Eilhermann',
		'Wordify',
		'beilhermannt@gravatar.com',
		5628107721,
		NULL,
		4
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'GAZ001',
		'Marty',
		'Gaze',
		'Nlounge',
		'mgazeu@etsy.com',
		3716803018,
		'5007667454076025',
		5
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'BRO001',
		'Venus',
		'Brolechan',
		'Edgewire',
		'vbrolechanl@cdbaby.com',
		4182889147,
		'372301443489333',
		8
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'UND001',
		'Paolo',
		'Underdown',
		NULL,
		'punderdownb@salon.com',
		7931967336,
		NULL,
		14
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'MEA001',
		'Jasmin',
		'Meacher',
		'Browsedrive',
		'jmeacher1b@salon.com',
		8875329768,
		'5002359780113194',
		7
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'GRI001',
		'Stanwood',
		'Gricewood',
		NULL,
		'sgricewoodp@unicef.org',
		4479195503,
		'5002354631798178',
		10
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'PLE001',
		'Sigvard',
		'Plevin',
		NULL,
		'splevinc@state.tx.us',
		5208491534,
		'5002357887676014',
		2
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'GAU001',
		'Constance',
		'Gauch',
		NULL,
		'cgauchf@creativecommons.org',
		9614350212,
		NULL,
		6
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'FER001',
		'Jilly',
		'Fernehough',
		'Trunyx',
		'jfernehough1c@cbslocal.com',
		1187428751,
		'5007668231195054',
		14
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'LYS001',
		'Wildon',
		'Lyster',
		'Kazio',
		'wlyster10@parallels.com',
		2538844400,
		NULL,
		10
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'LON001',
		'Martita',
		'Longmate',
		'Feedbug',
		'mlongmatee@typepad.com',
		7991665535,
		NULL,
		13
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'MCG001',
		'Angelica',
		'McGavin',
		NULL,
		'amcgavin15@cargocollective.com',
		7392702227,
		'5010124650641801',
		12
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'CRU001',
		'Matty',
		'Cruces',
		NULL,
		'mcruces18@arstechnica.com',
		7152904365,
		'372301642851556',
		4
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'HAT001',
		'Franklyn',
		'Hatherley',
		'Skiptube',
		'fhatherley8@arstechnica.com',
		8207416412,
		'372301554571887',
		8
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'BIL001',
		'Erika',
		'Bilson',
		NULL,
		'ebilson14@deviantart.com',
		3271467333,
		NULL,
		16
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'DEA001',
		'Drew',
		'Deane',
		'Flashset',
		'ddeanes@marketwatch.com',
		8889460459,
		'5002358855991542',
		13
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'HOO001',
		'Boris',
		'Hoovart',
		NULL,
		'bhoovartd@scientificamerican.com',
		4453980242,
		NULL,
		6
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'ANN001',
		'Rip',
		'Annesley',
		NULL,
		'rannesley19@naver.com',
		6876796278,
		NULL,
		1
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'CHA001',
		'Clare',
		'Chace',
		NULL,
		'cchace0@privacy.gov.au',
		7436121165,
		NULL,
		12
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'BUR002',
		'Charity',
		'Burr',
		NULL,
		'cburr1a@sphinn.com',
		8477827624,
		NULL,
		6
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'DOW001',
		'Norman',
		'Dowsey',
		'Rhyzio',
		'ndowsey3@gov.ab',
		5804642354,
		'5007667705030292',
		14
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'REP001',
		'Kyle',
		'Reppaport',
		'Zoonder',
		'kreppaport9@upenn.edu',
		1705354990,
		NULL,
		3
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'BOO001',
		'Morgan',
		'Boots',
		NULL,
		'mboots1d@mashable.com',
		6018601062,
		NULL,
		2
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'KNO001',
		'Floris',
		'Knowles',
		NULL,
		'fknowlesj@hexun.com',
		6906284045,
		'5007663795500328',
		3
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'HAN001',
		'Fernando',
		'Handke',
		'Eabox',
		'fhandkeo@nbcnews.com',
		7073124520,
		'5010128679576831',
		5
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'PAT001',
		'Andrea',
		'Patek',
		NULL,
		'apatek@wufoo.com',
		4129573902,
		NULL,
		13
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'VIT001',
		'Dom',
		'Vittery',
		NULL,
		'dvittery2@kickstarter.com',
		4964352152,
		'372301694670987',
		15
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'WIL001',
		'Lee',
		'Wilshere',
		NULL,
		'lwilshereq@foxnews.com',
		8607641978,
		NULL,
		9
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'SOM001',
		'Melissa',
		'Sommer',
		'Gigaclub',
		'msommer13@godaddy.com',
		6369499691,
		NULL,
		4
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'LOB001',
		'Vanda',
		'Lobell',
		'Blogtag',
		'vlobellg@globo.com',
		8853267362,
		'5002353099888893',
		3
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'BUR001',
		'Bert',
		'Burdess',
		'Zoovu',
		'bburdessw@fotki.com',
		6979636429,
		'5007666713848547',
		7
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'CAT001',
		'Alicia',
		'Cathro',
		'Mydo',
		'acathro6@techcrunch.com',
		9254669971,
		'372301318053644',
		13
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'SIM001',
		'Veronica',
		'Simonin',
		NULL,
		'vsimonini@patch.com',
		3124808950,
		'5002356792057740',
		11
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'COR001',
		'Mary',
		'Corpes',
		'Einti',
		'mcorpesa@mapquest.com',
		5164557732,
		'5007669883853354',
		9
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'NOT001',
		'Alli',
		'Note',
		'Roodel',
		'anoter@t.co',
		1455510396,
		NULL,
		4
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'GRE001',
		'Nichole',
		'Greiswood',
		NULL,
		'ngreiswoody@msu.edu',
		3183488833,
		'5007669585311644',
		7
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'JOB001',
		'Dorene',
		'Jobbing',
		'Riffwire',
		'djobbing11@mozilla.com',
		4839702712,
		NULL,
		8
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'DON001',
		'Georges',
		'Doniso',
		'Ozu',
		'gdoniso16@disqus.com',
		3493222744,
		'372301997634037',
		6
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'TOO001',
		'Roger',
		'Tootal',
		NULL,
		'rtootaln@weebly.com',
		4657355251,
		'372301224236036',
		10
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'COL001',
		'Loren',
		'Coleby',
		NULL,
		'lcoleby5@amazon.co.jp',
		6578726039,
		'5002357020090909',
		13
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'HAC001',
		'Lisbeth',
		'Hachard',
		NULL,
		'lhachard17@gizmodo.com',
		9112373678,
		'5002354883962100',
		14
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'DEC001',
		'Irwinn',
		'DeCarlo',
		NULL,
		'idecarlom@scribd.com',
		8394044663,
		NULL,
		2
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'SYN001',
		'Bert',
		'Synan',
		NULL,
		'bsynanh@unblog.fr',
		2175023834,
		'372301072057047',
		1
	);

INSERT INTO
	DESKHOLDER (
		DESKHOLDERID,
		FIRSTNAME,
		LASTNAME,
		COMPANYNAME,
		EMAILADDRESS,
		CELLPHONENUMBER,
		CREDITCARDNUMBER,
		REFERRALSOURCECODE
	)
VALUES
	(
		'JAQ001',
		'Gratiana',
		'Jaquemar',
		NULL,
		'gjaquemarx@oaic.gov.au',
		5043969448,
		'372301127375733',
		6
	);

-- Insert Into LeaseType
INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(7, 'Virtual Weekly');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(5, 'Two Year');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(1, 'Monthly');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(9, 'Shared Lease');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(8, 'Virtual Monthly');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(4, 'One Year');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(2, 'Six Months');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(3, 'Weekly');

INSERT INTO
	LEASETYPE (LEASETYPENUMBER, LEASETYPEDESCRIPTION)
VALUES
	(6, 'Part-Time');

-- Insert Into Lease
INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		241,
		TO_TIMESTAMP('18-Jun-2025', 'DD-Mon-YYYY'),
		TO_TIMESTAMP('23-Apr-2027', 'DD-Mon-YYYY'),
		0.00,
		0.00,
		179,
		'GRE001',
		4
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		214,
		TO_TIMESTAMP('23-Dec-2023', 'DD-Mon-YYYY'),
		NULL,
		687.59,
		1718.98,
		148,
		'LON001',
		6
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		188,
		TO_TIMESTAMP('08-Oct-2023', 'DD-Mon-YYYY'),
		NULL,
		134.40,
		336.00,
		128,
		'EIL001',
		6
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		185,
		TO_TIMESTAMP('28-Apr-2026', 'DD-Mon-YYYY'),
		NULL,
		108.00,
		270.00,
		174,
		'HAC001',
		3
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		172,
		TO_TIMESTAMP('08-Feb-2024', 'DD-Mon-YYYY'),
		NULL,
		132.00,
		330.00,
		228,
		'LOB001',
		1
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		127,
		TO_TIMESTAMP('25-Feb-2025', 'DD-Mon-YYYY'),
		NULL,
		125.08,
		312.71,
		248,
		'COR001',
		4
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		175,
		TO_TIMESTAMP('28-Apr-2025', 'DD-Mon-YYYY'),
		NULL,
		8.40,
		21.00,
		248,
		'DON001',
		3
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		203,
		TO_TIMESTAMP('10-Mar-2026', 'DD-Mon-YYYY'),
		NULL,
		0.00,
		0.00,
		156,
		'FER001',
		3
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		159,
		TO_TIMESTAMP('18-Feb-2025', 'DD-Mon-YYYY'),
		NULL,
		36.00,
		90.00,
		156,
		'KNO001',
		3
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		103,
		TO_TIMESTAMP('18-Apr-2025', 'DD-Mon-YYYY'),
		NULL,
		0.00,
		0.00,
		228,
		'LOB001',
		3
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		113,
		TO_TIMESTAMP('31-Mar-2026', 'DD-Mon-YYYY'),
		TO_TIMESTAMP('23-Dec-2027', 'DD-Mon-YYYY'),
		21.60,
		54.00,
		245,
		'LON001',
		5
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		107,
		TO_TIMESTAMP('20-Jun-2026', 'DD-Mon-YYYY'),
		NULL,
		0.00,
		0.00,
		207,
		'VIT001',
		5
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		236,
		TO_TIMESTAMP('08-Jan-2027', 'DD-Mon-YYYY'),
		NULL,
		365.98,
		914.96,
		129,
		'BRO001',
		2
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		114,
		TO_TIMESTAMP('30-Apr-2025', 'DD-Mon-YYYY'),
		TO_TIMESTAMP('25-Aug-2029', 'DD-Mon-YYYY'),
		11.40,
		28.50,
		223,
		'JOB001',
		4
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		131,
		TO_TIMESTAMP('18-Apr-2025', 'DD-Mon-YYYY'),
		NULL,
		0.00,
		0.00,
		129,
		'SYN001',
		2
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		247,
		TO_TIMESTAMP('07-Jul-2026', 'DD-Mon-YYYY'),
		NULL,
		0.00,
		0.00,
		233,
		'DEA001',
		3
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		153,
		TO_TIMESTAMP('28-Apr-2024', 'DD-Mon-YYYY'),
		TO_TIMESTAMP('02-Oct-2027', 'DD-Mon-YYYY'),
		200.00,
		500.00,
		172,
		'UND001',
		2
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		88,
		TO_TIMESTAMP('01-Oct-2026', 'DD-Mon-YYYY'),
		NULL,
		28.80,
		72.00,
		196,
		'CAT001',
		2
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		156,
		TO_TIMESTAMP('18-Aug-2025', 'DD-Mon-YYYY'),
		NULL,
		800.00,
		2000.00,
		245,
		'VIT001',
		1
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		221,
		TO_TIMESTAMP('16-May-2024', 'DD-Mon-YYYY'),
		TO_TIMESTAMP('01-Feb-2027', 'DD-Mon-YYYY'),
		1397.90,
		3494.75,
		223,
		'COL001',
		4
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		85,
		TO_TIMESTAMP('03-Sep-2025', 'DD-Mon-YYYY'),
		NULL,
		626.10,
		1565.25,
		204,
		'PAT001',
		5
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		204,
		TO_TIMESTAMP('28-Apr-2026', 'DD-Mon-YYYY'),
		TO_TIMESTAMP('12-Apr-2028', 'DD-Mon-YYYY'),
		24.00,
		60.00,
		145,
		'ING001',
		6
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		198,
		TO_TIMESTAMP('27-Aug-2026', 'DD-Mon-YYYY'),
		NULL,
		60.00,
		150.00,
		128,
		'WIL001',
		6
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		211,
		TO_TIMESTAMP('03-Apr-2024', 'DD-Mon-YYYY'),
		NULL,
		43.80,
		109.49,
		128,
		'HAT001',
		4
	);

INSERT INTO
	LEASE (
		LEASENUMBER,
		STARTDATE,
		ENDDATE,
		TOTALLEASECOST,
		TOTALLEASEPRICE,
		OFFICENUMBER,
		DESKHOLDERID,
		LEASETYPENUMBER
	)
VALUES
	(
		168,
		TO_TIMESTAMP('14-Oct-2025', 'DD-Mon-YYYY'),
		NULL,
		997.19,
		2492.98,
		196,
		'BUR001',
		2
	);

-- Insert Into OfficeAddOn
INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(1, 'Office Rent', 0.00, 0.00, 0.00);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(7, 'Postage', 1.00, 3.00, 5.00);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		10,
		'Power Strip Surge Protector (6 outlet)',
		29.99,
		49.99,
		NULL
	);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		14,
		'Video Conferencing Equipment Access (1 hour)',
		250.00,
		500.00,
		NULL
	);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		5,
		'Photocopy (black and white)',
		0.50,
		1.50,
		NULL
	);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		9,
		'Commission of Oaths (per document)',
		15.00,
		45.00,
		NULL
	);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		8,
		'Boardroom Rental (30 minutes)',
		25.00,
		75.00,
		10.00
	);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		12,
		'Laptop Docking Station (USBC)',
		69.99,
		94.99,
		NULL
	);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(2, 'Damage Deposit', 0.00, 1500.00, NULL);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(3, 'Access Card Deposit', 25.00, 50.00, NULL);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(4, 'Internet (per month)', 19.99, 59.99, NULL);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(11, 'Desk Lamp (LED)', 59.99, 69.99, NULL);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(6, 'Photocopy (colour)', 0.75, 2.25, NULL);

INSERT INTO
	OFFICEADDON (
		ADDONNUMBER,
		ADDONDESCRIPTION,
		CURRENTCOST,
		CURRENTPRICE,
		DISCOUNT
	)
VALUES
	(
		13,
		'Keyboard and Mouse (wireless)',
		39.99,
		59.99,
		NULL
	);

-- Insert Into Invoice
INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		140,
		TO_TIMESTAMP('02-Jul-2024 10:17:33', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		92.50,
		1850.00,
		221
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		240,
		TO_TIMESTAMP('29-Nov-2025 13:42:53', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		8.40,
		167.98,
		168
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		310,
		TO_TIMESTAMP('01-Nov-2026 18:46:36', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		3.60,
		72.00,
		88
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		130,
		TO_TIMESTAMP('02-Jun-2024 11:35:33', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		10.00,
		200.00,
		153
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		325,
		TO_TIMESTAMP('01-Nov-2026 17:34:51', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		14.25,
		284.96,
		236
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		220,
		TO_TIMESTAMP('01-Oct-2025 16:18:30', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		95.00,
		1900.00,
		156
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		250,
		TO_TIMESTAMP('29-Nov-2025 10:11:07', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		75.00,
		1500.00,
		168
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		255,
		TO_TIMESTAMP('01-May-2026 17:40:46', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		2.70,
		54.00,
		113
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		215,
		TO_TIMESTAMP('01-Jun-2025 16:16:47', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		1.43,
		28.50,
		114
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		150,
		TO_TIMESTAMP('02-Jul-2024 15:30:40', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		77.74,
		1554.75,
		221
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		320,
		TO_TIMESTAMP('01-Nov-2026 08:23:32', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		31.50,
		630.00,
		236
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		110,
		TO_TIMESTAMP('02-Jun-2024 11:39:46', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		5.47,
		109.49,
		211
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		85,
		TO_TIMESTAMP('30-Nov-2023 11:49:23', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		1.35,
		27.00,
		188
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		100,
		TO_TIMESTAMP('01-Apr-2024 15:46:20', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		16.50,
		330.00,
		172
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		230,
		TO_TIMESTAMP('01-Nov-2025 09:47:49', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		78.26,
		1565.25,
		85
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		225,
		TO_TIMESTAMP('01-Oct-2025 08:15:32', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		5.00,
		100.00,
		156
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		175,
		TO_TIMESTAMP('31-Mar-2025 18:03:21', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		0.83,
		16.50,
		127
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		265,
		TO_TIMESTAMP('01-Jun-2026 16:51:04', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		13.50,
		270.00,
		185
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		170,
		TO_TIMESTAMP('31-Mar-2025 13:07:31', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		2.81,
		56.25,
		127
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		235,
		TO_TIMESTAMP('29-Nov-2025 17:55:13', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		41.25,
		825.00,
		168
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		280,
		TO_TIMESTAMP('01-Jun-2026 10:22:48', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		0.68,
		13.50,
		204
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		200,
		TO_TIMESTAMP('01-Jun-2025 16:50:36', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		1.05,
		21.00,
		175
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		295,
		TO_TIMESTAMP('01-Oct-2026 11:15:42', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		5.00,
		100.00,
		198
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		180,
		TO_TIMESTAMP('31-Mar-2025 13:21:17', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		12.00,
		239.96,
		127
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		160,
		TO_TIMESTAMP('31-Mar-2025 14:24:07', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		4.50,
		90.00,
		159
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		95,
		TO_TIMESTAMP('30-Jan-2024 13:38:33', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		10.50,
		209.98,
		214
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		145,
		TO_TIMESTAMP('02-Jul-2024 13:59:11', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		4.50,
		90.00,
		221
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		300,
		TO_TIMESTAMP('01-Oct-2026 15:03:58', 'DD-Mon-YYYY HH24:MI:SS'),
		'Y',
		2.50,
		50.00,
		198
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		120,
		TO_TIMESTAMP('02-Jun-2024 13:40:04', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		15.00,
		300.00,
		153
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		90,
		TO_TIMESTAMP('30-Jan-2024 14:51:27', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		75.45,
		1509.00,
		214
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		270,
		TO_TIMESTAMP('01-Jun-2026 09:56:56', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		2.33,
		46.50,
		204
	);

INSERT INTO
	INVOICE (
		INVOICENUMBER,
		INVOICEDATE,
		PAIDYN,
		INVOICEGST,
		INVOICETOTAL,
		LEASENUMBER
	)
VALUES
	(
		80,
		TO_TIMESTAMP('30-Nov-2023 12:07:57', 'DD-Mon-YYYY HH24:MI:SS'),
		'N',
		15.45,
		309.00,
		188
	);

-- Insert Into InvoiceItem
INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(215, 5, 19, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(90, 5, 6, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(90, 2, 1, 0.00, 1500.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(230, 2, 1, 0.00, 1500.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(325, 4, 4, 19.99, 59.99);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(265, 8, 3, 25.00, 75.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(270, 6, 8, 0.75, 2.25);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(320, 9, 4, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(95, 9, 2, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(140, 1, 1, 700.00, 1750.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(145, 9, 2, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(310, 7, 24, 1.00, 3.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(130, 3, 4, 25.00, 50.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(240, 4, 2, 19.99, 59.99);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(170, 6, 25, 0.75, 2.25);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(100, 3, 3, 25.00, 50.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(85, 7, 4, 1.00, 3.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(270, 5, 19, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(200, 7, 7, 1.00, 3.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(80, 7, 8, 1.00, 3.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(320, 8, 4, 25.00, 75.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(300, 3, 1, 25.00, 50.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(150, 2, 1, 0.00, 1500.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(225, 3, 2, 25.00, 50.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(235, 8, 1, 25.00, 75.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(110, 6, 22, 0.75, 2.25);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(110, 4, 1, 19.99, 59.99);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(80, 9, 3, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(220, 1, 1, 760.00, 1900.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(175, 5, 11, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(120, 8, 4, 25.00, 75.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(100, 9, 4, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(240, 7, 16, 1.00, 3.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(280, 5, 9, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(85, 5, 10, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(160, 9, 2, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(140, 3, 2, 25.00, 50.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(95, 4, 2, 19.99, 59.99);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(150, 5, 23, 0.50, 1.50);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(180, 4, 4, 19.99, 59.99);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(80, 8, 2, 25.00, 75.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(235, 1, 1, 300.00, 750.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(295, 3, 2, 25.00, 50.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(250, 2, 1, 0.00, 1500.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(265, 9, 1, 15.00, 45.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(255, 6, 24, 0.75, 2.25);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(325, 7, 15, 1.00, 3.00);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(150, 6, 9, 0.75, 2.25);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(230, 6, 29, 0.75, 2.25);

INSERT INTO
	INVOICEITEM (
		INVOICENUMBER,
		ADDONNUMBER,
		QUANTITYSOLD,
		INVOICEADDONCOST,
		INVOICEADDONPRICE
	)
VALUES
	(320, 3, 3, 25.00, 50.00);

-- 1. Write a Select statement to display the OfficeNumber, MonthlyRent, and SquareFootage for all offices in the Office table.
SELECT
	OFFICENUMBER,
	MONTHLYRENT,
	SQUAREFOOTAGE
FROM
	OFFICE;

-- 2. Write a Select statement to display the FirstName, LastName, and EmailAddress of all desk holders whose ReferralSourceCode is 2.
SELECT
	FIRSTNAME,
	LASTNAME,
	EMAILADDRESS
FROM
	DESKHOLDER
WHERE
	REFERRALSOURCECODE = 2;

-- 3. Write a Select statement that displays the DeskHolderID and a concatenated full name column called "Desk Holder Name" from the DeskHolder table.
SELECT
	DESKHOLDERID,
	FIRSTNAME || ' ' || LASTNAME AS "Desk Holder Name"
FROM
	DESKHOLDER;

-- 4. Write a Select statement that displays the OfficeNumber, MonthlyRent, and WindowQuantity for offices where the MonthlyRent is greater than 1200 and the WindowQuantity is at least 2.
SELECT
	OFFICENUMBER,
	MONTHLYRENT,
	WINDOWQUANTITY
FROM
	OFFICE
WHERE
	MONTHLYRENT > 1200
	AND WINDOWQUANTITY >= 2;

-- 5. Write a select statement that displays all office add-ons whose AddonDescription begins with the letter 'C' using the LIKE operator.
SELECT
	ADDONNUMBER,
	ADDONDESCRIPTION,
	CURRENTCOST,
	CURRENTPRICE
FROM
	OFFICEADDON
WHERE
	ADDONDESCRIPTION LIKE 'C%';

-- 6. Write a Select statement that displays the FirstName and LastName of desk holders whose last name contains the letters “son” anywhere in the value using the LIKE operator.
SELECT
	FIRSTNAME,
	LASTNAME
FROM
	DESKHOLDER
WHERE
	LASTNAME LIKE '%son%';

-- 7. Write a Select statement that displays the DeskHolderID, FirstName, and LastName of desk holders whose DeskHolderID starts with exactly three uppercase letters followed by three numbers using a PostgreSQL regular expression.
SELECT
	DESKHOLDERID,
	FIRSTNAME,
	LASTNAME
FROM
	DESKHOLDER
WHERE
	DESKHOLDERID ~ '^[A-Z]{3}[0-9]{3}$';


-- 8, Write a Select statement that displays the InvoiceNumber, InvoiceDate, and InvoiceTotal from the Invoice table sorted by InvoiceTotal in descending order.

SELECT INVOICENUMBER, INVOICEDATE, INVOICETOTAL
FROM INVOICE
ORDER BY INVOICETOTAL DESC;

-- 9. Write a Select statement that displays a unique list of ReferralSourceCode values from the DeskHolder table sorted in ascending order.

SELECT REFERRALSOURCECODE
FROM DESKHOLDER
ORDER BY REFERRALSOURCECODE ASC;

-- 10. Write a Select statement that displays the LeaseNumber, OfficeNumber, and TotalLeasePrice for leases where the TotalLeasePrice is between 500 and 20000, sorted from highest lease price to lowest lease price.

SELECT LEASENUMBER, OFFICENUMBER, TOTALLEASEPRICE
FROM LEASE
WHERE TOTALLEASEPRICE BETWEEN 500 AND 20000
ORDER BY TOTALLEASEPRICE DESC;

