-- drop tables
DROP TABLE IF EXISTS INVOICEITEM;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS OFFICEADDON;
DROP TABLE IF EXISTS LEASE;
DROP TABLE IF EXISTS LEASETYPE;
DROP TABLE IF EXISTS DESKHOLDER;
DROP TABLE IF EXISTS OFFICE;
DROP TABLE IF EXISTS REFERRALSOURCE;
DROP TABLE IF EXISTS OFFICETYPE;
CREATE TABLE OFFICETYPE
(
	OFFICETYPECODE DECIMAL(2, 0) CONSTRAINT PK_OFFICE_OFFICETYPECODE PRIMARY KEY CONSTRAINT NN_OFFICE_OFFICETYPECODE NOT NULL,
	OFFICETYPEDESCRIPTION VARCHAR(35) CONSTRAINT NN_OFFICE_OFFICETYPEDESCRIPTION NOT NULL
);

SELECT
	*
FROM
	OFFICETYPE;

CREATE TABLE REFERRALSOURCE
(
	REFERRALSOURCECODE DECIMAL(2, 0) CONSTRAINT PK_REFERRALSOURCE_REFERRALSOURCECODE PRIMARY KEY CONSTRAINT NN_REFERRALSOURCE_REFERRALSOURCECODE NOT NULL,
	REFERRALSOURCEDESCRIPTION VARCHAR(30) CONSTRAINT NN_REFERRALSOURCE_REFERRALSOURCEDESCRIPTION NOT NULL
);

SELECT
	*
FROM
	REFERRALSOURCE;

CREATE TABLE OFFICE
(
	OFFICENUMBER DECIMAL(3, 0) CONSTRAINT PK_OFFICE_OFFICENUMBER PRIMARY KEY CONSTRAINT NN_OFFICE_OFFICENUMBER NOT NULL,
	MONTHLYRENT DECIMAL(6, 2) CONSTRAINT NN_OFFICE_MONTHLYRENT NOT NULL,
	SQUAREFOOTAGE DECIMAL(6, 2) CONSTRAINT NN_OFFICE_SQUAREFOOTAGE NOT NULL,
	BOOKSHELFYN CHAR(1) CONSTRAINT NN_OFFICE_BOOKSHELFYN NOT NULL,
	EXTRAFILINGCABINETYN CHAR(1) CONSTRAINT NN_OFFICE_EXTRAFILINGCABINETYN NOT NULL,
	MEETINGTABLEYN CHAR(1) CONSTRAINT NN_OFFICE_MEETINGTABLEYN NOT NULL,
	WINDOWQUANTITY DECIMAL(2, 0) CONSTRAINT NN_OFFICE_WINDOWQUANTITY NOT NULL,
	WINDOWSTATUS CHAR(1) CONSTRAINT NN_OFFICE_WINDOWSTATUS NOT NULL,
	OFFICETYPECODE DECIMAL(2, 0) CONSTRAINT NN_OFFICE_OFFICETYPECODE NOT NULL CONSTRAINT FK_OFFICE_OFFICETYPECODE_OFFICETYPE_OFFICETYPECODE REFERENCES OFFICETYPE (OFFICETYPECODE)
);

SELECT
	*
FROM
	OFFICE;

CREATE TABLE DESKHOLDER
(
	DESKHOLDERID CHAR(6) CONSTRAINT PK_DESKHOLDER_DESKHOLDERID PRIMARY KEY CONSTRAINT NN_DESKHOLDER_DESKHOLDERID NOT NULL,
	FIRSTNAME VARCHAR(35) CONSTRAINT NN_DESKHOLDER_FIRSTNAME NOT NULL,
	LASTNAME VARCHAR(40) CONSTRAINT NN_DESKHOLDER_LASTNAME NOT NULL,
	COMPANYNAME VARCHAR(55) CONSTRAINT NN_DESKHOLDER_COMPANYNAME NULL,
	EMAILADDRESS VARCHAR(75) CONSTRAINT NN_DESKHOLDER_EMAILADDRESS NOT NULL,
	CELLPHONENUMBER CHAR(10) CONSTRAINT NN_DESKHOLDER_CELLPHONENUMBER NOT NULL,
	CREDITCARDNUMBER VARCHAR(16) CONSTRAINT NL_DESKHOLDER_CREDITCARDNUMBER NULL,
	REFERRALSOURCECODE DECIMAL(2, 0) CONSTRAINT NN_DESKHOLDER_REFERRALSOURCECODE NOT NULL CONSTRAINT FK_DESKHOLDER_REFERRALSOURCECODE_RS_REFERRALSOURCECODE REFERENCES REFERRALSOURCE (REFERRALSOURCECODE)
);

SELECT
	*
FROM
	DESKHOLDER;

CREATE TABLE LEASETYPE
(
	LEASETYPENUMBER DECIMAL(2, 0) CONSTRAINT PK_LEASETYPE_LEASETYPENUMBER PRIMARY KEY CONSTRAINT NN_LEASETYPE_LEASETYPENUMBER NOT NULL,
	LEASETYPEDESCRIPTION VARCHAR(50) CONSTRAINT NN_LEASETYPE_LEASETYPEDESCRIPTION NOT NULL
);

SELECT
	*
FROM
	LEASETYPE;

CREATE TABLE LEASE
(
	LEASENUMBER DECIMAL(6, 0) CONSTRAINT PK_LEASE_LEASENUMBER PRIMARY KEY CONSTRAINT NN_LEASE_LEASENUMBER NOT NULL,
	STARTDATE TIMESTAMP CONSTRAINT NN_LEASE_STARTDATE NOT NULL,
	ENDDATE TIMESTAMP CONSTRAINT NL_LEASE_ENDDATE NULL,
	TOTALLEASECOST DECIMAL(15, 2) CONSTRAINT NL_LEASE_TOTALLEASECOST NULL,
	TOTALLEASEPRICE DECIMAL(15, 2) CONSTRAINT NL_LEASE_TOTALLEASEPRICE NULL,
	OFFICENUMBER DECIMAL(3, 0) CONSTRAINT NN_LEASE_OFFICENUMBER NOT NULL CONSTRAINT FK_LEASE_OFFICENUMBER REFERENCES OFFICE (OFFICENUMBER),
	DESKHOLDERID CHAR(6) CONSTRAINT NN_LEASE_DESKHOLDERID NOT NULL CONSTRAINT FK_LEASE_DESKHOLDERID_DESKHOLDER_DESKHOLDERID REFERENCES DESKHOLDER (DESKHOLDERID),
	LEASETYPENUMBER DECIMAL(2, 0) CONSTRAINT NN_LEASE_LEASETYPENUMBER NOT NULL CONSTRAINT FK_LEASE_LEASETYPENUMBER_LEASETYPE_LEASETYPENUMBER REFERENCES LEASETYPE (LEASETYPENUMBER)
);

SELECT
	*
FROM
	LEASE;

CREATE TABLE OFFICEADDON
(
	ADDONNUMBER DECIMAL(4, 0) CONSTRAINT PK_OFFICEADDON_AONUM PRIMARY KEY CONSTRAINT NN_OFFICEADDON_AONUM NOT NULL,
	ADDONDESCRIPTION VARCHAR(45) CONSTRAINT NN_OFFICEADDON_ADDONDESCRIPTION NOT NULL,
	CURRENTCOST DECIMAL(6, 2) CONSTRAINT NN_OFFICEADDON_CURRENTCOST NOT NULL,
	CURRENTPRICE DECIMAL(6, 2) CONSTRAINT NN_OFFICEADDON_CURRENTPRICE NOT NULL,
	DISCOUNT DECIMAL(3, 0) CONSTRAINT NN_OFFICEADDON_DISCOUNT NULL
);

SELECT
	*
FROM
	OFFICEADDON;

CREATE TABLE INVOICE
(
	INVOICENUMBER DECIMAL(6, 0) CONSTRAINT PK_INVOICE_INVOICENUMBER PRIMARY KEY CONSTRAINT NN_INVOICE_INVOICENUMBER NOT NULL,
	INVOICEDATE TIMESTAMP CONSTRAINT NN_INVOICE_INVOICEDATE NOT NULL,
	PAIDYN CHAR(1) CONSTRAINT NL_INVOICE_PAIDYN NULL,
	INVOICEGST DECIMAL(9, 2) CONSTRAINT NN_INVOICE_INVOICEGST NOT NULL,
	INVOICETOTAL DECIMAL(11, 2) CONSTRAINT NN_INVOICE_INVOICETOTAL NOT NULL,
	LEASENUMBER DECIMAL(6, 0) CONSTRAINT NN_INVOICE_LEASENUMBER NOT NULL CONSTRAINT FK_INVOICE_LEASENUMBER_LEASE_LEASENUMBER REFERENCES LEASE (LEASENUMBER)
);

SELECT
	*
FROM
	INVOICE;

CREATE TABLE INVOICEITEM
(
	INVOICENUMBER DECIMAL(6, 0) CONSTRAINT NN_INVOICEITEM_INVOICENUMBER NOT NULL CONSTRAINT FK_INVOICEITEM_INVOICENUMBER_INVOICE_INVOICENUMBER REFERENCES INVOICE (INVOICENUMBER),
	ADDONNUMBER DECIMAL(4, 0) CONSTRAINT NN_INVOICEITEM_ADDONNUMBER NOT NULL CONSTRAINT FK_INVOICEITEM_ADDONNUMBER_OFFICEADDON_ADDONNUMBER REFERENCES OFFICEADDON (ADDONNUMBER),
	QUANTITYSOLD DECIMAL(5, 0) CONSTRAINT NN_INVOICEITEM_QUANTITYSOLD NOT NULL,
	INVOICEADDONCOST DECIMAL(6, 2) CONSTRAINT NN_INVOICEITEM_INVOICEADDONCOST NOT NULL,
	INVOICEADDONPRICE DECIMAL(6, 2) CONSTRAINT NN_INVOICEITEM_INVOICEADDONPRICE NOT NULL,
	CONSTRAINT PK_INVOICEITEM_INVOICENUMBER_ADDONNUMBER PRIMARY KEY (INVOICENUMBER, ADDONNUMBER)
);

SELECT
	*
FROM
	INVOICEITEM;

CREATE INDEX IX_OFFICE_OFFICETYPECODE ON OFFICE (OFFICETYPECODE);
CREATE INDEX IX_DESKHOLDER_REFERRALSOURCECODE ON DESKHOLDER (REFERRALSOURCECODE);
CREATE INDEX IX_LEASE_OFFICENUMBER ON LEASE (OFFICENUMBER);
CREATE INDEX IX_LEASE_DESKHOLDERID ON LEASE (DESKHOLDERID);
CREATE INDEX IX_LEASE_LEASETYPENUMBER ON LEASE (LEASETYPENUMBER);
CREATE INDEX IX_INVOICEITEM_INVOICENUMBER ON INVOICEITEM (INVOICENUMBER);
CREATE INDEX IX_INVOICEITEM_ADDONNUMBER ON INVOICEITEM (ADDONNUMBER);
CREATE INDEX IX_INVOICE_LEASENUMBER ON INVOICE (LEASENUMBER);